name: Continuous Build

on: pull_request

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
        env:
          GO_INTEGRATION_TESTS_SERVER_KEY_ID: ${{ secrets.KEY }}
          GO_INTEGRATION_TESTS_SERVER_KEY_SECRET: ${{ secrets.SECRET }}
          GO_INTEGRATION_TESTS_SERVER_API_URL: ${{ secrets.SERVER_API_URL }}
